version: "3"

services:
  community-fixing-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: community-fixing-api-local
    image: community-fixing-api:local
    ports:
       - 20079:80
    labels:
       - "traefik.enable=true"
       - "traefik.http.routers.community-fixing-api.entrypoints=web"
      #  - "traefik.http.routers.community-fixing-api.rule=Host(`www.rj.test`)"
       - traefik.http.routers.community-fixing-api.rule=HostRegexp(`{catchall:.*}`)
       - "traefik.http.services.community-fixing-api.loadbalancer.server.port=80"
    volumes:
      - .:/var/www/html
      - ~/.cache/composer:/var/www/.composer/cache
    networks:
      - devops_default
          
networks:
  devops_default:
    external: true
